# coding = utf-8

from feedback.models import FragebogenUE2020
from feedback.parser.ergebnisse.parser import Parser


class ParserUE2020(Parser):
    @classmethod
    def create_fragebogen(cls, veranst, frageb):
        FragebogenUE2020.objects.create(
            veranstaltung=veranst,
            fach=cls.parse_fach_16(frageb[1]),
            abschluss=cls.parse_abschluss_16(frageb[3]),
            semester=cls.parse_semester_16(frageb[4]),
            geschlecht=cls.parse_geschlecht_16(frageb[5]),
            studienberechtigung=cls.parse_studienberechtigung(frageb[6]),
            ue_wie_oft_besucht=cls.parse_int(frageb[7]),
            ue_besuch_ueberschneidung=cls.parse_boolean(frageb[8]),
            ue_besuch_qualitaet=cls.parse_boolean(frageb[9]),
            ue_besuch_verhaeltnisse=cls.parse_boolean(frageb[10]),
            ue_besuch_privat=cls.parse_boolean(frageb[11]),
            ue_besuch_elearning=cls.parse_boolean(frageb[12]),
            ue_besuch_zufrueh=cls.parse_boolean(frageb[13]),
            ue_besuch_sonstiges=cls.parse_boolean(frageb[14]),
            ue_3_1=cls.parse_int(frageb[16]),
            ue_3_2=cls.parse_int(frageb[17]),
            ue_3_3=cls.parse_int(frageb[18]),
            ue_3_4=cls.parse_int(frageb[19]),
            ue_3_5=cls.parse_int(frageb[20]),
            ue_3_6=cls.parse_int(frageb[21]),
            ue_3_7=cls.parse_int(frageb[22]),
            ue_3_8=cls.parse_int(frageb[23]),
            ue_4_1=cls.parse_int(frageb[24]),
            ue_4_2=cls.parse_int(frageb[25]),
            ue_4_3=cls.parse_int(frageb[26]),
            ue_4_4=cls.parse_int(frageb[27]),
            ue_4_5=cls.parse_int(frageb[28]),
            ue_4_6=cls.parse_int(frageb[29]),
            ue_4_7=cls.parse_int(frageb[30]),
            ue_4_8=cls.parse_int(frageb[31]),
            ue_4_9=cls.parse_int(frageb[32]),
            ue_4_10=cls.parse_geschwindigkeit16(frageb[33]),
            ue_4_11=cls.parse_geschwindigkeit16(frageb[34]),
            kennziffer=cls.parse_int(frageb[35]),
            ue_5_2=cls.parse_int(frageb[36]),
            ue_5_3=cls.parse_int(frageb[37]),
            ue_5_4=cls.parse_int(frageb[38]),
            ue_5_5=cls.parse_int(frageb[39]),
            ue_5_6=cls.parse_int(frageb[40]),
            ue_5_7=cls.parse_int(frageb[41]),
            ue_5_8=cls.parse_int(frageb[42]),
            ue_5_9=cls.parse_int(frageb[43]),
            ue_5_10=cls.parse_int(frageb[44]),
            ue_5_11=cls.parse_int(frageb[45]),
            ue_5_12=cls.parse_int(frageb[46]),
            ue_5_13=cls.parse_int(frageb[47]),
            ue_5_14=cls.parse_int(frageb[48]),
            ue_5_15=cls.parse_int(frageb[49]),
            ue_5_16=cls.parse_int(frageb[50]),
            ue_6_1=cls.parse_int(frageb[51]),
            ue_6_2=cls.parse_int(frageb[52]),
            ue_7_1=cls.parse_extrazeit(frageb[54]),
            ue_7_2=cls.parse_int(frageb[55]),
            ue_7_3=cls.parse_int(frageb[56]),
        )
