# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-02 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_auto_20161002_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importveranstaltung',
            name='veranstalter',
            field=models.ManyToManyField(blank=True, to='feedback.ImportPerson'),
        ),
        migrations.AlterField(
            model_name='veranstaltung',
            name='ergebnis_empfaenger',
            field=models.ManyToManyField(blank=True, help_text='An diese Personen werden die Ergebnisse per E-Mail geschickt.', related_name='ergebnis_empfaenger', to='feedback.Person', verbose_name='Empf\xe4nger der Ergebnisse'),
        ),
        migrations.AlterField(
            model_name='veranstaltung',
            name='veranstalter',
            field=models.ManyToManyField(blank=True, help_text='Alle Personen, die mit der Veranstaltung befasst sind und z.B. Frageb\xf6gen bestellen k\xf6nnen sollen.', to='feedback.Person'),
        ),
    ]
