# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 22:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_auto_20161002_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='importcategory',
            name='rel_level',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='importveranstaltung',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ivs', to='feedback.ImportCategory'),
        ),
    ]
