# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 17:43


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_auto_20161122_1951'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlternativVorname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vorname', models.CharField(blank=True, max_length=40, verbose_name='first name')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.Person')),
            ],
        ),
    ]
