# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 20:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_auto_20161122_1951'),
        ('feedback', '0004_auto_20161121_2200'),
    ]

    operations = [
    ]
