# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_alternativvorname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternativvorname',
            name='vorname',
            field=models.CharField(blank=True, max_length=30, verbose_name='first name'),
        ),
    ]
