# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 22:26


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0006_auto_20161128_1806'),
        ('feedback', '0005_merge_20161126_2007'),
    ]

    operations = [
    ]
