# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-04 17:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0007_veranstaltung_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status_von', models.IntegerField()),
                ('status_nach', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VeranstaltungStatus',
            fields=[
            ],
            options={
                'verbose_name': 'Status der Veranstaltung',
                'proxy': True,
                'verbose_name_plural': 'Status der Veranstaltungen',
            },
            bases=('feedback.veranstaltung',),
        ),
        migrations.AddField(
            model_name='log',
            name='veranstaltung',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.Veranstaltung'),
        ),
    ]
