# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 09:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0007_veranstaltung_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarcodeAllowedState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_state', models.IntegerField(choices=[(100, 'Angelegt'), (600, 'Gedruckt'), (700, 'Versandt'), (800, 'B\xf6gen eingegangen'), (900, 'B\xf6gen gescannt')], null=True, unique=True)),
                ('barcode_scanner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.BarcodeScanner')),
            ],
        ),
    ]
