# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-08 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0008_barcodeallowedstate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barcodescanner',
            name='token',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
