# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-04 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0008_auto_20161204_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='veranstaltung',
            field=models.CharField(max_length=150),
        ),
    ]
