# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-04 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0009_auto_20161204_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='veranstaltung',
            name='old_status',
            field=models.IntegerField(choices=[('de', 'Deutsch'), ('en', 'Englisch')], default=100),
        ),
    ]
