# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 13:44


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0010_veranstaltung_old_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={'verbose_name': 'Log', 'verbose_name_plural': 'Logs'},
        ),
        migrations.AddField(
            model_name='log',
            name='verursacher',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='veranstaltung',
            name='old_status',
            field=models.IntegerField(choices=[(100, 'Angelegt'), (600, 'Gedruckt'), (700, 'Versandt'), (800, 'B\xf6gen eingegangen'), (900, 'B\xf6gen gescannt')], default=100),
        ),
    ]
