# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-05 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0011_auto_20161205_1344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='veranstaltung',
            new_name='name',
        ),
        migrations.AddField(
            model_name='log',
            name='interface',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
