# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-05 23:54


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0012_auto_20161205_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='status_nach',
            field=models.IntegerField(choices=[(100, 'Angelegt'), (600, 'Gedruckt'), (700, 'Versandt'), (800, 'B\xf6gen eingegangen'), (900, 'B\xf6gen gescannt')], default=100),
        ),
        migrations.AlterField(
            model_name='log',
            name='status_von',
            field=models.IntegerField(choices=[(100, 'Angelegt'), (600, 'Gedruckt'), (700, 'Versandt'), (800, 'B\xf6gen eingegangen'), (900, 'B\xf6gen gescannt')], default=100),
        ),
    ]
