# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-06 00:00


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0013_auto_20161205_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veranstaltung',
            name='old_status',
            field=models.IntegerField(blank=True, choices=[(100, 'Angelegt'), (600, 'Gedruckt'), (700, 'Versandt'), (800, 'B\xf6gen eingegangen'), (900, 'B\xf6gen gescannt')], default=None),
        ),
    ]
