# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-06 00:12


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0014_auto_20161206_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veranstaltung',
            name='old_status',
            field=models.IntegerField(choices=[(100, 'Angelegt'), (600, 'Gedruckt'), (700, 'Versandt'), (800, 'B\xf6gen eingegangen'), (900, 'B\xf6gen gescannt')], default=100),
        ),
    ]
