# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-08 14:42


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0015_auto_20161206_0012'),
        ('feedback', '0009_auto_20161208_0928'),
    ]

    operations = [
    ]
