# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-08 19:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0017_auto_20161208_1532'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='status_nach',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='log',
            name='status_von',
        ),
        migrations.RemoveField(
            model_name='veranstaltung',
            name='old_status',
        ),
    ]
