# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-09 14:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0018_auto_20161208_1949'),
        ('feedback', '0018_importveranstaltung_is_attended_course'),
    ]

    operations = [
    ]
