# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-09 14:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0007_merge_20161128_2226'),
        ('feedback', '0019_merge_20161209_1404'),
    ]

    operations = [
    ]
