# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 17:08


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0020_merge_20161209_1436'),
        ('feedback', '0020_auto_20161213_2056'),
    ]

    operations = [
    ]
