# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-24 17:14


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0022_auto_20161223_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailEndung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_suffix', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EmailSekretaerin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Fachgebiet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('kuerzel', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Fachgebiet',
                'verbose_name_plural': 'Fachgebiete',
            },
        ),
        migrations.AddField(
            model_name='emailsekretaerin',
            name='fachgebiet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fg_sekretaerin', to='feedback.Fachgebiet'),
        ),
        migrations.AddField(
            model_name='emailendung',
            name='fachgebiet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fg_endung', to='feedback.Fachgebiet'),
        ),
        migrations.AddField(
            model_name='emailendung',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person', to='feedback.Person'),
        ),
    ]
