# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-26 19:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0024_auto_20161224_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='FachgebietEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suffix', models.EmailField(help_text='Vor dem @-Symbol kann beliebiges stehen. Wichtig ist nur der Text, der dahinter steht.', max_length=254)),
                ('email_sekretaerin', models.EmailField(max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name='emailsuffix',
            name='person',
        ),
        migrations.AlterModelOptions(
            name='fachgebiet',
            options={},
        ),
        migrations.RemoveField(
            model_name='fachgebiet',
            name='email_sek',
        ),
        migrations.RemoveField(
            model_name='fachgebiet',
            name='email_suffix',
        ),
        migrations.AlterField(
            model_name='fachgebiet',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.DeleteModel(
            name='EmailSekretaerin',
        ),
        migrations.DeleteModel(
            name='EmailSuffix',
        ),
        migrations.AddField(
            model_name='fachgebietemail',
            name='fachgebiet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fachgebiet_emailsuffix', to='feedback.Fachgebiet'),
        ),
    ]
