# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 11:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0026_auto_20161226_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='fachgebiet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='feedback.Fachgebiet'),
        ),
    ]
