# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 11:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0027_auto_20161227_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fachgebietemail',
            name='suffix',
        ),
        migrations.AddField(
            model_name='fachgebietemail',
            name='email_suffix',
            field=models.CharField(help_text='Hier soll der Domainname einer Email-Adresse eines Fachgebiets stehen.', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='fachgebietemail',
            name='fachgebiet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fachgebiet', to='feedback.Fachgebiet'),
        ),
    ]
