# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 15:36


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0031_veranstaltung_primaerdozent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veranstaltung',
            name='primaerdozent',
            field=models.ForeignKey(blank=True, help_text='Die Person, die im Anschreiben erw\xe4hnt wird', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primaerdozent', to='feedback.Person'),
        ),
    ]
