# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-14 17:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0030_auto_20170112_1308'),
        ('feedback', '0031_person_fachgebiet'),
    ]

    operations = [
    ]
