# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0034_auto_20170207_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barcodeallowedstate',
            name='allow_state',
            field=models.IntegerField(choices=[(100, 'Angelegt'), (200, 'Bestellung ge\xf6ffnet'), (300, 'Keine Evaluation'), (310, 'Keine Evaluation final'), (500, 'Bestellung liegt vor'), (510, 'Bestellung wird verarbeitet'), (600, 'Gedruckt'), (700, 'Versandt'), (800, 'B\xf6gen eingegangen'), (900, 'B\xf6gen gescannt'), (1000, 'Ergebnisse versandt')], null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='status',
            field=models.IntegerField(choices=[(100, 'Angelegt'), (200, 'Bestellung ge\xf6ffnet'), (300, 'Keine Evaluation'), (310, 'Keine Evaluation final'), (500, 'Bestellung liegt vor'), (510, 'Bestellung wird verarbeitet'), (600, 'Gedruckt'), (700, 'Versandt'), (800, 'B\xf6gen eingegangen'), (900, 'B\xf6gen gescannt'), (1000, 'Ergebnisse versandt')], default=100),
        ),
        migrations.AlterField(
            model_name='veranstaltung',
            name='status',
            field=models.IntegerField(choices=[(100, 'Angelegt'), (200, 'Bestellung ge\xf6ffnet'), (300, 'Keine Evaluation'), (310, 'Keine Evaluation final'), (500, 'Bestellung liegt vor'), (510, 'Bestellung wird verarbeitet'), (600, 'Gedruckt'), (700, 'Versandt'), (800, 'B\xf6gen eingegangen'), (900, 'B\xf6gen gescannt'), (1000, 'Ergebnisse versandt')], default=100),
        ),
    ]
