# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0034_auto_20170207_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fragebogen2008',
            name='abschluss',
            field=models.CharField(blank=True, choices=[('bsc', 'Bachelor'), ('msc', 'Master'), ('dipl', 'Diplom'), ('lehr', 'Lehramt'), ('sonst', 'anderer Abschluss')], max_length=5),
        ),
        migrations.AlterField(
            model_name='fragebogen2008',
            name='empfehlung',
            field=models.CharField(blank=True, choices=[('j', 'ja'), ('n', 'nein')], max_length=1),
        ),
        migrations.AlterField(
            model_name='fragebogen2008',
            name='fach',
            field=models.CharField(blank=True, choices=[('inf', 'Informatik'), ('math', 'Mathematik'), ('ce', 'Computational Engineering'), ('ist', 'Informationssystemtechnik'), ('etit', 'Elektrotechnik'), ('psyit', 'Psychologie in IT'), ('winf', 'Wirtschaftsinformatik'), ('sonst', 'etwas anderes')], max_length=5),
        ),
        migrations.AlterField(
            model_name='fragebogen2008',
            name='ue_besuch_privat',
            field=models.CharField(blank=True, choices=[('j', 'ja'), ('n', 'nein')], max_length=1),
        ),
        migrations.AlterField(
            model_name='fragebogen2008',
            name='ue_besuch_qualitaet',
            field=models.CharField(blank=True, choices=[('j', 'ja'), ('n', 'nein')], max_length=1),
        ),
        migrations.AlterField(
            model_name='fragebogen2008',
            name='ue_besuch_sonstiges',
            field=models.CharField(blank=True, choices=[('j', 'ja'), ('n', 'nein')], max_length=1),
        ),
        migrations.AlterField(
            model_name='fragebogen2008',
            name='ue_besuch_ueberschneidung',
            field=models.CharField(blank=True, choices=[('j', 'ja'), ('n', 'nein')], max_length=1),
        ),
        migrations.AlterField(
            model_name='fragebogen2008',
            name='ue_besuch_verhaeltnisse',
            field=models.CharField(blank=True, choices=[('j', 'ja'), ('n', 'nein')], max_length=1),
        ),
        migrations.AlterField(
            model_name='fragebogen2008',
            name='ue_i2',
            field=models.CharField(blank=True, choices=[('h', 'zu hoch'), ('n', 'zu niedrig')], max_length=1),
        ),
        migrations.AlterField(
            model_name='fragebogen2008',
            name='v_besuch_privat',
            field=models.CharField(blank=True, choices=[('j', 'ja'), ('n', 'nein')], max_length=1),
        ),
        migrations.AlterField(
            model_name='fragebogen2008',
            name='v_besuch_qualitaet',
            field=models.CharField(blank=True, choices=[('j', 'ja'), ('n', 'nein')], max_length=1),
        ),
        migrations.AlterField(
            model_name='fragebogen2008',
            name='v_besuch_sonstiges',
            field=models.CharField(blank=True, choices=[('j', 'ja'), ('n', 'nein')], max_length=1),
        ),
        migrations.AlterField(
            model_name='fragebogen2008',
            name='v_besuch_ueberschneidung',
            field=models.CharField(blank=True, choices=[('j', 'ja'), ('n', 'nein')], max_length=1),
        ),
        migrations.AlterField(
            model_name='fragebogen2008',
            name='v_besuch_verhaeltnisse',
            field=models.CharField(blank=True, choices=[('j', 'ja'), ('n', 'nein')], max_length=1),
        ),
        migrations.AlterField(
            model_name='fragebogen2008',
            name='v_f2',
            field=models.CharField(blank=True, choices=[('s', 'zu schnell'), ('l', 'zu langsam')], max_length=1),
        ),
        migrations.AlterField(
            model_name='fragebogen2009',
            name='abschluss',
            field=models.CharField(blank=True, choices=[('bsc', 'Bachelor'), ('msc', 'Master'), ('dipl', 'Diplom'), ('lehr', 'Lehramt'), ('sonst', 'anderer Abschluss')], max_length=5),
        ),
        migrations.AlterField(
            model_name='fragebogen2009',
            name='fach',
            field=models.CharField(blank=True, choices=[('inf', 'Informatik'), ('math', 'Mathematik'), ('ce', 'Computational Engineering'), ('ist', 'Informationssystemtechnik'), ('etit', 'Elektrotechnik'), ('psyit', 'Psychologie in IT'), ('winf', 'Wirtschaftsinformatik'), ('sonst', 'etwas anderes')], max_length=5),
        ),
        migrations.AlterField(
            model_name='fragebogen2009',
            name='ue_besuch_privat',
            field=models.CharField(blank=True, choices=[('j', 'ja'), ('n', 'nein')], max_length=1),
        ),
        migrations.AlterField(
            model_name='fragebogen2009',
            name='ue_besuch_qualitaet',
            field=models.CharField(blank=True, choices=[('j', 'ja'), ('n', 'nein')], max_length=1),
        ),
        migrations.AlterField(
            model_name='fragebogen2009',
            name='ue_besuch_sonstiges',
            field=models.CharField(blank=True, choices=[('j', 'ja'), ('n', 'nein')], max_length=1),
        ),
        migrations.AlterField(
            model_name='fragebogen2009',
            name='ue_besuch_ueberschneidung',
            field=models.CharField(blank=True, choices=[('j', 'ja'), ('n', 'nein')], max_length=1),
        ),
        migrations.AlterField(
            model_name='fragebogen2009',
            name='ue_besuch_verhaeltnisse',
            field=models.CharField(blank=True, choices=[('j', 'ja'), ('n', 'nein')], max_length=1),
        ),
        migrations.AlterField(
            model_name='fragebogen2009',
            name='ue_i2',
            field=models.CharField(blank=True, choices=[('h', 'zu hoch'), ('n', 'zu niedrig')], max_length=1),
        ),
        migrations.AlterField(
            model_name='fragebogen2009',
            name='v_besuch_privat',
            field=models.CharField(blank=True, choices=[('j', 'ja'), ('n', 'nein')], max_length=1),
        ),
        migrations.AlterField(
            model_name='fragebogen2009',
            name='v_besuch_qualitaet',
            field=models.CharField(blank=True, choices=[('j', 'ja'), ('n', 'nein')], max_length=1),
        ),
        migrations.AlterField(
            model_name='fragebogen2009',
            name='v_besuch_sonstiges',
            field=models.CharField(blank=True, choices=[('j', 'ja'), ('n', 'nein')], max_length=1),
        ),
        migrations.AlterField(
            model_name='fragebogen2009',
            name='v_besuch_ueberschneidung',
            field=models.CharField(blank=True, choices=[('j', 'ja'), ('n', 'nein')], max_length=1),
        ),
        migrations.AlterField(
            model_name='fragebogen2009',
            name='v_besuch_verhaeltnisse',
            field=models.CharField(blank=True, choices=[('j', 'ja'), ('n', 'nein')], max_length=1),
        ),
        migrations.AlterField(
            model_name='fragebogen2009',
            name='v_f2',
            field=models.CharField(blank=True, choices=[('s', 'zu schnell'), ('l', 'zu langsam')], max_length=1),
        ),
        migrations.AlterField(
            model_name='fragebogen2012',
            name='abschluss',
            field=models.CharField(blank=True, choices=[('bsc', 'Bachelor'), ('msc', 'Master'), ('dipl', 'Diplom'), ('lehr', 'Lehramt'), ('sonst', 'anderer Abschluss')], max_length=5),
        ),
        migrations.AlterField(
            model_name='fragebogen2012',
            name='fach',
            field=models.CharField(blank=True, choices=[('inf', 'Informatik'), ('math', 'Mathematik'), ('ce', 'Computational Engineering'), ('ist', 'Informationssystemtechnik'), ('etit', 'Elektrotechnik'), ('psyit', 'Psychologie in IT'), ('winf', 'Wirtschaftsinformatik'), ('sonst', 'etwas anderes')], max_length=5),
        ),
        migrations.AlterField(
            model_name='fragebogen2012',
            name='geschlecht',
            field=models.CharField(blank=True, choices=[('w', 'weiblich'), ('m', 'männlich'), ('s', 'sonstiges')], max_length=1),
        ),
        migrations.AlterField(
            model_name='fragebogen2012',
            name='semester',
            field=models.CharField(blank=True, choices=[('1-2', '1-2'), ('3-4', '3-4'), ('5-6', '5-6'), ('>=7', '>=7')], max_length=3),
        ),
        migrations.AlterField(
            model_name='fragebogen2012',
            name='studienberechtigung',
            field=models.CharField(blank=True, choices=[('d', 'Deutschland'), ('o', 'anderes Land')], max_length=1),
        ),
        migrations.AlterField(
            model_name='fragebogen2012',
            name='ue_13a',
            field=models.CharField(blank=True, choices=[('h', 'zu hoch'), ('n', 'zu niedrig')], max_length=1),
        ),
        migrations.AlterField(
            model_name='fragebogen2012',
            name='ue_besuch_privat',
            field=models.CharField(blank=True, choices=[('j', 'ja'), ('n', 'nein')], max_length=1),
        ),
        migrations.AlterField(
            model_name='fragebogen2012',
            name='ue_besuch_qualitaet',
            field=models.CharField(blank=True, choices=[('j', 'ja'), ('n', 'nein')], max_length=1),
        ),
        migrations.AlterField(
            model_name='fragebogen2012',
            name='ue_besuch_sonstiges',
            field=models.CharField(blank=True, choices=[('j', 'ja'), ('n', 'nein')], max_length=1),
        ),
        migrations.AlterField(
            model_name='fragebogen2012',
            name='ue_besuch_ueberschneidung',
            field=models.CharField(blank=True, choices=[('j', 'ja'), ('n', 'nein')], max_length=1),
        ),
        migrations.AlterField(
            model_name='fragebogen2012',
            name='ue_besuch_verhaeltnisse',
            field=models.CharField(blank=True, choices=[('j', 'ja'), ('n', 'nein')], max_length=1),
        ),
        migrations.AlterField(
            model_name='fragebogen2012',
            name='v_10a',
            field=models.CharField(blank=True, choices=[('s', 'zu schnell'), ('l', 'zu langsam')], max_length=1),
        ),
        migrations.AlterField(
            model_name='fragebogen2012',
            name='v_besuch_privat',
            field=models.CharField(blank=True, choices=[('j', 'ja'), ('n', 'nein')], max_length=1),
        ),
        migrations.AlterField(
            model_name='fragebogen2012',
            name='v_besuch_qualitaet',
            field=models.CharField(blank=True, choices=[('j', 'ja'), ('n', 'nein')], max_length=1),
        ),
        migrations.AlterField(
            model_name='fragebogen2012',
            name='v_besuch_sonstiges',
            field=models.CharField(blank=True, choices=[('j', 'ja'), ('n', 'nein')], max_length=1),
        ),
        migrations.AlterField(
            model_name='fragebogen2012',
            name='v_besuch_ueberschneidung',
            field=models.CharField(blank=True, choices=[('j', 'ja'), ('n', 'nein')], max_length=1),
        ),
        migrations.AlterField(
            model_name='fragebogen2012',
            name='v_besuch_verhaeltnisse',
            field=models.CharField(blank=True, choices=[('j', 'ja'), ('n', 'nein')], max_length=1),
        ),
        migrations.AlterField(
            model_name='fragebogen2016',
            name='abschluss',
            field=models.CharField(blank=True, choices=[('bsc', 'Bachelor'), ('msc', 'Master'), ('dipl', 'Diplom'), ('lehr', 'Lehramt'), ('sonst', 'anderer Abschluss')], max_length=5),
        ),
        migrations.AlterField(
            model_name='fragebogen2016',
            name='fach',
            field=models.CharField(blank=True, choices=[('inf', 'Informatik'), ('math', 'Mathematik'), ('ce', 'Computational Engineering'), ('ist', 'Informationssystemtechnik'), ('etit', 'Elektrotechnik'), ('psyit', 'Psychologie in IT'), ('winf', 'Wirtschaftsinformatik'), ('sonst', 'etwas anderes')], max_length=5),
        ),
        migrations.AlterField(
            model_name='fragebogen2016',
            name='geschlecht',
            field=models.CharField(blank=True, choices=[('w', 'weiblich'), ('m', 'männlich'), ('s', 'sonstiges')], max_length=1),
        ),
        migrations.AlterField(
            model_name='fragebogen2016',
            name='male_veranstaltung_gehoert',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '<=4')], max_length=1),
        ),
        migrations.AlterField(
            model_name='fragebogen2016',
            name='pflichveranstaltung',
            field=models.CharField(blank=True, choices=[('j', 'ja'), ('n', 'nein')], max_length=1),
        ),
        migrations.AlterField(
            model_name='fragebogen2016',
            name='pruefung_angetreten',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2')], max_length=1),
        ),
        migrations.AlterField(
            model_name='fragebogen2016',
            name='semester',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '>=10')], max_length=4),
        ),
        migrations.AlterField(
            model_name='fragebogen2016',
            name='studienberechtigung',
            field=models.CharField(blank=True, choices=[('d', 'Deutschland'), ('o', 'anderes Land')], max_length=1),
        ),
        migrations.AlterField(
            model_name='fragebogen2016',
            name='v_6_1',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '0.5'), ('2', '1'), ('3', '2'), ('4', '3'), ('5', '4'), ('6', '5'), ('7', '>=5')], max_length=1),
        ),
        migrations.AlterField(
            model_name='fragebogen2016',
            name='v_6_8',
            field=models.CharField(blank=True, choices=[('j', 'ja'), ('n', 'nein')], max_length=1),
        ),
        migrations.AlterField(
            model_name='fragebogen2016',
            name='v_besuch_elearning',
            field=models.CharField(blank=True, choices=[('j', 'ja'), ('n', 'nein')], max_length=1),
        ),
        migrations.AlterField(
            model_name='fragebogen2016',
            name='v_besuch_privat',
            field=models.CharField(blank=True, choices=[('j', 'ja'), ('n', 'nein')], max_length=1),
        ),
        migrations.AlterField(
            model_name='fragebogen2016',
            name='v_besuch_qualitaet',
            field=models.CharField(blank=True, choices=[('j', 'ja'), ('n', 'nein')], max_length=1),
        ),
        migrations.AlterField(
            model_name='fragebogen2016',
            name='v_besuch_sonstiges',
            field=models.CharField(blank=True, choices=[('j', 'ja'), ('n', 'nein')], max_length=1),
        ),
        migrations.AlterField(
            model_name='fragebogen2016',
            name='v_besuch_ueberschneidung',
            field=models.CharField(blank=True, choices=[('j', 'ja'), ('n', 'nein')], max_length=1),
        ),
        migrations.AlterField(
            model_name='fragebogen2016',
            name='v_besuch_verhaeltnisse',
            field=models.CharField(blank=True, choices=[('j', 'ja'), ('n', 'nein')], max_length=1),
        ),
        migrations.AlterField(
            model_name='fragebogen2016',
            name='v_besuch_zufrueh',
            field=models.CharField(blank=True, choices=[('j', 'ja'), ('n', 'nein')], max_length=1),
        ),
    ]
