# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 14:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0036_auto_20170319_1423'),
        ('feedback', '0032_merge_20170114_1715'),
    ]

    operations = [
    ]
