# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0037_merge_20170321_1400'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='barcodeallowedstate',
            options={'verbose_name': 'Erlaubter Zustand', 'verbose_name_plural': 'Erlaubte Zust\xe4nde'},
        ),
        migrations.AlterField(
            model_name='barcodeallowedstate',
            name='allow_state',
            field=models.IntegerField(choices=[(100, 'Angelegt'), (200, 'Bestellung ge\xf6ffnet'), (300, 'Keine Evaluation'), (310, 'Keine Evaluation final'), (500, 'Bestellung liegt vor'), (510, 'Bestellung wird verarbeitet'), (600, 'Gedruckt'), (700, 'Versandt'), (800, 'B\xf6gen eingegangen'), (900, 'B\xf6gen gescannt'), (1000, 'Ergebnisse versandt')], null=True),
        ),
    ]
