# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 16:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0038_auto_20170321_1438'),
        ('feedback', '0035_auto_20170210_2100'),
    ]

    operations = [
    ]
