# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-25 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0040_veranstaltung_digitale_eval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veranstaltung',
            name='digitale_eval',
            field=models.BooleanField(default=False, help_text='Die Evaluation soll digital durchgeführt werden, d.h. Sie erhalten einen Bogen TAN-Nummern, welche Sie an die Studiernden verteilen können. Die Studierenden füllen die Evaluation dann online aus.', verbose_name='Digitale Evaluation'),
        ),
    ]
