# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-06 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0043_auto_20190618_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veranstaltung',
            name='digitale_eval',
            field=models.BooleanField(default=False, help_text='Die Evaluation soll digital durchgeführt werden. Sie erhalten entsprechend viele TAN-Nummern auf Thermopapier, welche Sie an die Studiernden verteilen können. Die Studierenden füllen die Evaluation dann online aus.', verbose_name='Digitale Evaluation'),
        ),
    ]
