# Generated by Django 2.2.12 on 2020-06-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0046_auto_20200525_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veranstaltung',
            name='digitale_eval_type',
            field=models.CharField(choices=[('T', 'TANs'), ('L', 'Losung')], default='T', help_text='Es werden generell zwei Typen von Verteilungsmethoden angeboten: Bei TANs erhalten Sie eine Excel Datei mit einer Liste aller TANs, welche Sie beispielsweise mithilfe von moodle verteilen können (eine Anleitung dazu wird bereitgestellt). Beim losungsbasierten Verfahren erhalten Sie einen einfachen, mehrfachbenutzbaren Link zum Onlinefragebogen.', max_length=1, verbose_name='Digitaler Evaluationstyp'),
        ),
    ]
