# Generated by Django 2.2.16 on 2020-09-25 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0047_auto_20200603_1218'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Einstellung',
        ),
    ]
