# Generated by Django 2.2.24 on 2021-12-15 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0049_auto_20211215_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fragebogen2020',
            name='v_7_3',
        ),
    ]
