# Generated by Django 3.0.14 on 2024-08-17 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0051_auto_20230604_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importveranstaltung',
            name='typ',
            field=models.CharField(choices=[('v', 'Vorlesung'), ('vu', 'Vorlesung mit Übung'), ('pr', 'Praktikum'), ('se', 'Seminar')], max_length=2),
        ),
    ]
