# Generated by Django 5.1.1 on 2024-11-19 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0052_auto_20240817_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternativvorname',
            name='vorname',
            field=models.CharField(blank=True, max_length=30, verbose_name='Vorname'),
        ),
        migrations.AlterField(
            model_name='person',
            name='nachname',
            field=models.CharField(blank=True, max_length=30, verbose_name='Nachname'),
        ),
        migrations.AlterField(
            model_name='person',
            name='vorname',
            field=models.CharField(blank=True, max_length=30, verbose_name='Vorname'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='nachname',
            field=models.CharField(max_length=30, verbose_name='Nachname'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='vorname',
            field=models.CharField(max_length=30, verbose_name='Vorname'),
        ),
    ]
