# Generated by Django 5.1.1 on 2024-11-23 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0053_alter_alternativvorname_vorname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternativvorname',
            name='vorname',
            field=models.CharField(blank=True, max_length=30, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='emailendung',
            name='fachgebiet',
            field=models.ForeignKey(blank=True, help_text='Hier soll der Domainname einer Email-Adresse eines Fachgebiets stehen.', on_delete=django.db.models.deletion.CASCADE, to='feedback.fachgebiet', verbose_name='Fachgebiet'),
        ),
        migrations.AlterField(
            model_name='fachgebietemail',
            name='fachgebiet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fachgebiet', to='feedback.fachgebiet', verbose_name='Fachgebiet'),
        ),
        migrations.AlterField(
            model_name='person',
            name='fachgebiet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='feedback.fachgebiet', verbose_name='Fachgebiet'),
        ),
        migrations.AlterField(
            model_name='person',
            name='nachname',
            field=models.CharField(blank=True, max_length=30, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='vorname',
            field=models.CharField(blank=True, max_length=30, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='fragebogen',
            field=models.CharField(choices=[('2008', 'Fragebogen 2008'), ('2009', 'Fragebogen 2009'), ('2012', 'Fragebogen 2012'), ('2016', 'Fragebogen 2016'), ('2020', 'Fragebogen 2020')], help_text='Verwendete Version des Fragebogens.', max_length=5, verbose_name='Fragebogen'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='sichtbarkeit',
            field=models.CharField(choices=[('ADM', 'Administratoren'), ('VER', 'Veranstalter'), ('ALL', 'alle (öffentlich)')], help_text='Sichtbarkeit der Evaluationsergebnisse.<br /><em>Administratoren:</em> nur für Mitglieder des Feedback-Teams<br /><em>Veranstalter:</em> Veranstalter und Mitglieder des Feedback-Teams<br /><em>alle (öffentlich):</em> alle (beschränkt auf das Uninetz)<br />', max_length=3, verbose_name='Sichtbarkeit'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='vollerhebung',
            field=models.BooleanField(default=False, verbose_name='Vollerhebung'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='anmerkung',
            field=models.CharField(max_length=100, verbose_name='Anmerkung'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='nachname',
            field=models.CharField(max_length=30, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='veranstaltung',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.veranstaltung', verbose_name='Veranstaltung'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='vorname',
            field=models.CharField(max_length=30, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='veranstaltung',
            name='anzahl',
            field=models.IntegerField(blank=True, null=True, verbose_name='Anzahl'),
        ),
        migrations.AlterField(
            model_name='veranstaltung',
            name='evaluieren',
            field=models.BooleanField(choices=[(True, 'Ja'), (False, 'Nein')], default=True, verbose_name='Evaluieren'),
        ),
        migrations.AlterField(
            model_name='veranstaltung',
            name='grundstudium',
            field=models.BooleanField(verbose_name='Grundstudium'),
        ),
        migrations.AlterField(
            model_name='veranstaltung',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='veranstaltung',
            name='primaerdozent',
            field=models.ForeignKey(blank=True, help_text='Die Person, die im Anschreiben erwähnt wird', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primaerdozent', to='feedback.person', verbose_name='Primaerdozent'),
        ),
        migrations.AlterField(
            model_name='veranstaltung',
            name='sprache',
            field=models.CharField(blank=True, choices=[('de', 'Deutsch'), ('en', 'Englisch')], max_length=2, null=True, verbose_name='Sprache'),
        ),
        migrations.AlterField(
            model_name='veranstaltung',
            name='typ',
            field=models.CharField(choices=[('v', 'Vorlesung'), ('vu', 'Vorlesung mit Übung'), ('pr', 'Praktikum'), ('se', 'Seminar')], help_text='Wenn Ihre Vorlesung keine Übung hat wählen Sie bitte <i>Vorlesung</i> aus', max_length=2, verbose_name='Typ'),
        ),
        migrations.AlterField(
            model_name='veranstaltung',
            name='veranstalter',
            field=models.ManyToManyField(blank=True, help_text='Alle Personen, die mit der Veranstaltung befasst sind und z.B. Fragebögen bestellen können sollen.', to='feedback.person', verbose_name='Veranstalter'),
        ),
        migrations.AlterField(
            model_name='veranstaltung',
            name='verantwortlich',
            field=models.ForeignKey(blank=True, help_text='Diese Person wird von uns bei Rückfragen kontaktiert und bekommt die Fragenbögen zugeschickt', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verantwortlich', to='feedback.person', verbose_name='Verantwortlich'),
        ),
        migrations.AlterField(
            model_name='veranstaltung',
            name='veroeffentlichen',
            field=models.BooleanField(choices=[(True, 'Ja'), (False, 'Nein')], default=True, verbose_name='Veroeffentlichen'),
        ),
    ]
