# Generated by Django 5.2.7 on 2025-11-09 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0056_fragebogenue2025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ergebnis2025',
            old_name='v_7_5',
            new_name='v_8_1',
        ),
        migrations.RenameField(
            model_name='ergebnis2025',
            old_name='v_7_5_count',
            new_name='v_8_1_count',
        ),
    ]
