# Generated by Django 5.2.8 on 2026-01-19 23:54

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0057_rename_v_7_5_ergebnis2025_v_8_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('old_email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Alte E-Mail')),
                ('new_email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Neue E-Mail')),
                ('new_email_otp_hash', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'The change request has been expired'), (1, 'Change link has been sent to the old email'), (2, 'New Email needs verification, OTP sent to new email'), (3, 'New email has been verified, email change has been completed')], db_index=True, default=1)),
                ('person_list_to_change', models.ManyToManyField(blank=True, help_text='Bitte wählen Sie alle Personen aus, deren E-Mail-Adresse geändert werden soll.', related_name='email_change_list', to='feedback.person', verbose_name='Personen')),
            ],
            options={
                'verbose_name': 'E-Mail-Änderung',
                'verbose_name_plural': 'E-Mail-Änderungen',
            },
        ),
    ]
