# Generated by Django 5.2.7 on 2025-11-30 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0058_ergebnisse2025_fragebogense2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='fragebogense2025',
            name='s_3_5',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
