# Generated by Django 5.2.8 on 2026-01-20 00:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0058_emailchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailchange',
            name='dynamic_expiry_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
