# Generated by Django 5.2.7 on 2025-12-01 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0059_fragebogense2025_s_3_5'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fragebogense2025',
            name='s_9_1',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fragebogense2025',
            name='s_9_2',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fragebogense2025',
            name='s_9_3',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
