# Generated by Django 5.2.8 on 2026-01-20 00:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0059_emailchange_dynamic_expiry_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailchange',
            name='dynamic_expiry_time',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='15 Minuten nach diesem Datum ist die Anfrage nicht mehr gültig.'),
        ),
        migrations.AlterField(
            model_name='emailchange',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'EXPIRED'), (1, 'LINK SENT'), (2, 'OTP SENT'), (3, 'COMPLETED SUCCESSFULLY')], db_index=True, default=1),
        ),
    ]
