# Generated by Django 5.2.8 on 2026-01-20 01:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0060_alter_emailchange_dynamic_expiry_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailchange',
            name='dynamic_expiry_time',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Ab dieser Zeitpunk wird berechnet, ob die Anfrage gültig ist.'),
        ),
    ]
