# Generated by Django 6.0.1 on 2026-04-19 23:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0061_alter_emailchange_dynamic_expiry_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailchange',
            name='dynamic_expiry_time',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Ab diesem Zeitpunk wird berechnet, ob die Anfrage gültig ist.'),
        ),
    ]
