# Generated by Django 6.0.4 on 2026-05-01 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0062_alter_emailchange_dynamic_expiry_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fragebogen2025',
            name='v_4_2',
            field=models.CharField(blank=True, default='', max_length=1),
            preserve_default=False,
        ),
    ]
